const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d'),empty=document.getElementById('empty'),size=document.getElementById('size'),download=document.getElementById('download'),result=document.getElementById('result'),resultImage=document.getElementById('resultImage'),saveLink=document.getElementById('saveLink');
let img=null,drag=false,dx=0,dy=0;
let eventData={name:"INNOVVISTA '14",title:"INNOVVISTA '14",subtitle:"OFFICIAL PARTICIPANT",slug:"innovvista14",bg:"#11182b",accent:"#9d91ff",text:"#ffffff",shape:"rounded",font:"noto"};
let badge={x:460,y:560,w:260,h:104};
const params=new URLSearchParams(location.search);
function slugify(s){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)}
function fontFamily(){return eventData.font==='malayalam'?'Noto Sans Malayalam, sans-serif':eventData.font==='system'?'system-ui, sans-serif':'Noto Sans, sans-serif'}
function loadEvent(){const raw=params.get('event');if(raw&&raw!=='innovvista14'){try{const d=JSON.parse(decodeURIComponent(atob(raw)));eventData={...eventData,...d}}catch(e){}}document.getElementById('eventPill').textContent=eventData.name;document.getElementById('editorTitle').textContent=eventData.name;document.getElementById('footerEvent').textContent=eventData.name}
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.closePath()}
function drawBadge(c,x,y,w,h,preview=false){const scale=w/260;const r=eventData.shape==='pill'?h/2:eventData.shape==='outline'?20:eventData.shape==='dark'?28:20;c.save();roundRect(c,x,y,w,h,r);if(eventData.shape==='outline'){c.fillStyle='rgba(0,0,0,.25)';c.fill();c.strokeStyle=eventData.accent;c.lineWidth=4*scale;c.stroke()}else{c.fillStyle=eventData.shape==='dark'?'rgba(8,12,25,.82)':eventData.bg;c.fill();c.strokeStyle=eventData.accent;c.lineWidth=3*scale;c.stroke()}c.fillStyle=eventData.accent;c.fillRect(x,y,Math.max(6,7*scale),h);const titleSize=Math.max(13,20*scale),subSize=Math.max(10,14*scale);c.fillStyle=eventData.text;c.font='800 '+titleSize+'px '+fontFamily();c.textBaseline='alphabetic';c.fillText(eventData.title,x+20*scale,y+39*scale);c.fillStyle=eventData.accent;c.font='700 '+subSize+'px '+fontFamily();c.fillText(eventData.subtitle,x+20*scale,y+69*scale);c.restore()}
function draw(){ctx.clearRect(0,0,720,720);if(!img){empty.style.display='grid';download.disabled=true;return}empty.style.display='none';download.disabled=false;const s=Math.max(720/img.width,720/img.height),w=img.width*s,h=img.height*s;ctx.drawImage(img,(720-w)/2,(720-h)/2,w,h);drawBadge(ctx,badge.x,badge.y,badge.w,badge.h)}
function load(file){if(!file)return;const r=new FileReader();r.onload=e=>{img=new Image();img.onload=()=>{badge={x:460,y:560,w:+size.value,h:+size.value*.4};result.hidden=true;draw()};img.src=e.target.result};r.readAsDataURL(file)}
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*720/r.height}}
function renderPreview(){const c=document.getElementById('badgePreview'),p=c.getContext('2d');p.clearRect(0,0,c.width,c.height);p.fillStyle='#080d18';p.fillRect(0,0,c.width,c.height);drawBadge(p,45,75,430,110,true)}
function syncDesigner(){document.getElementById('eventName').value=eventData.name;document.getElementById('badgeTitle').value=eventData.title;document.getElementById('badgeSubtitle').value=eventData.subtitle;document.getElementById('badgeColor').value=eventData.bg;document.getElementById('accentColor').value=eventData.accent;document.getElementById('textColor').value=eventData.text;document.getElementById('badgeShape').value=eventData.shape;document.getElementById('badgeFont').value=eventData.font;renderPreview()}
function bindDesigner(){const ids=['eventName','badgeTitle','badgeSubtitle','badgeColor','accentColor','textColor','badgeShape','badgeFont'];ids.forEach(id=>document.getElementById(id).addEventListener('input',()=>{eventData.name=document.getElementById('eventName').value||'My Event';eventData.title=document.getElementById('badgeTitle').value||eventData.name;eventData.subtitle=document.getElementById('badgeSubtitle').value||'OFFICIAL PARTICIPANT';eventData.bg=document.getElementById('badgeColor').value;eventData.accent=document.getElementById('accentColor').value;eventData.text=document.getElementById('textColor').value;eventData.shape=document.getElementById('badgeShape').value;eventData.font=document.getElementById('badgeFont').value;renderPreview()}))}
document.getElementById('englishTab').onclick=()=>{document.getElementById('englishTab').classList.add('active');document.getElementById('malayalamTab').classList.remove('active');document.getElementById('badgeTitle').value='MY EVENT';document.getElementById('badgeSubtitle').value='OFFICIAL PARTICIPANT';document.getElementById('badgeFont').value='noto';document.getElementById('badgeTitle').dispatchEvent(new Event('input'))};
document.getElementById('malayalamTab').onclick=()=>{document.getElementById('malayalamTab').classList.add('active');document.getElementById('englishTab').classList.remove('active');document.getElementById('badgeTitle').value='എന്റെ പരിപാടി';document.getElementById('badgeSubtitle').value='ഔദ്യോഗിക പങ്കാളി';document.getElementById('badgeFont').value='malayalam';document.getElementById('badgeTitle').dispatchEvent(new Event('input'))};
document.getElementById('cameraInput').onchange=e=>load(e.target.files[0]);document.getElementById('uploadInput').onchange=e=>load(e.target.files[0]);
size.oninput=()=>{badge.w=+size.value;badge.h=badge.w*.4;draw()};document.getElementById('resetBtn').onclick=()=>{if(img){badge={x:460,y:560,w:+size.value,h:+size.value*.4};draw()}};
canvas.onpointerdown=e=>{if(!img)return;const p=pos(e);if(p.x>=badge.x&&p.x<=badge.x+badge.w&&p.y>=badge.y&&p.y<=badge.y+badge.h){drag=true;dx=p.x-badge.x;dy=p.y-badge.y;canvas.setPointerCapture(e.pointerId)}};canvas.onpointermove=e=>{if(!drag)return;const p=pos(e);badge.x=Math.max(0,Math.min(720-badge.w,p.x-dx));badge.y=Math.max(0,Math.min(720-badge.h,p.y-dy));draw()};canvas.onpointerup=()=>drag=false;
download.onclick=()=>{if(!img)return;const data=canvas.toDataURL('image/jpeg',.92);resultImage.src=data;saveLink.href=data;result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'center'})};
const organizerBtn=document.getElementById('organizerBtn'),panel=document.getElementById('organizerPanel');organizerBtn.onclick=()=>{panel.hidden=false;syncDesigner();panel.scrollIntoView({behavior:'smooth'});};document.getElementById('closeOrganizer').onclick=()=>panel.hidden=true;
document.getElementById('createEvent').onclick=()=>{eventData.slug=slugify(eventData.name);const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(eventData))));const link=location.origin+location.pathname+'?event='+encodeURIComponent(encoded);document.getElementById('eventLink').value=link;document.getElementById('eventResult').hidden=false;new QRious({element:document.getElementById('qr'),value:link,size:240,level:'H'});document.getElementById('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(link);document.getElementById('copyLink').textContent='✓ Link Copied'}catch(e){document.getElementById('eventLink').select();document.execCommand('copy')}}};
loadEvent();bindDesigner();renderPreview();draw();